from .nodes.MattingUtils import NODE_CLASS_MAPPINGS as MATTING_NCM
from .nodes.MattingUtils import NODE_DISPLAY_NAME_MAPPINGS as MATTING_NDNM

NODE_CLASS_MAPPINGS = {
    **MATTING_NCM,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **MATTING_NDNM,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
